# Generated by Django 5.1.7 on 2025-03-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=255)),
                ('supplier_id', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': True,
            },
        ),
    ]
