# Generated by Django 5.1.7 on 2025-03-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_product_code_order_variant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='supplier_id',
            field=models.IntegerField(),
        ),
    ]
