# Generated by Django 4.2.20 on 2025-06-13 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_product_code_inventoryitem_product_id'),
        ('orders', '0003_alter_order_supplier_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='variant_id',
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='variant',
            field=models.ForeignKey(db_column='variant_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.productvariant', to_field='variant_code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
