# Generated by Django 4.2.20 on 2025-07-23 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(default='P00000', max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(default='일반', help_text='상품 카테고리 (예: 문구, 도서, 의류 등)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['product_id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_code', models.CharField(max_length=50, unique=True)),
                ('option', models.CharField(max_length=255)),
                ('stock', models.IntegerField(default=0)),
                ('min_stock', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('memo', models.TextField(blank=True, default='')),
                ('cost_price', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjustment', models.IntegerField(default=0)),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('return_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.inventoryitem')),
            ],
            options={
                'db_table': 'product_variants',
                'ordering': ['variant_code'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(help_text='보정 수량: 양수/음수 모두 가능')),
                ('reason', models.CharField(help_text='보정 사유 설명', max_length=255)),
                ('created_by', models.CharField(help_text='보정 작업 수행자(사용자명 또는 ID)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='inventory.productvariant')),
            ],
            options={
                'db_table': 'inventory_adjustments',
                'ordering': ['-created_at'],
            },
        ),
    ]
