# Generated by Django 4.2.20 on 2026-01-11 02:17

import apps.inventory.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryadjustment',
            name='month',
            field=models.IntegerField(default=apps.inventory.models.current_month),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='year',
            field=models.IntegerField(default=apps.inventory.models.current_year),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='big_category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='middle_category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='online_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='detail_option',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(default='일반', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='management_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'option', 'detail_option')},
        ),
        migrations.CreateModel(
            name='ProductVariantStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('warehouse_stock_start', models.IntegerField(default=0)),
                ('store_stock_start', models.IntegerField(default=0)),
                ('inbound_quantity', models.IntegerField(default=0)),
                ('store_sales', models.IntegerField(default=0)),
                ('online_sales', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productvariant')),
            ],
            options={
                'unique_together': {('year', 'month', 'variant')},
            },
        ),
    ]
