# Generated by Django 4.2.20 on 2025-09-09 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reason', models.CharField(blank=True, help_text='스냅샷 사유 (예: POS 덮어쓰기 전)', max_length=200)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventorySnapshotItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=64)),
                ('variant_code', models.CharField(db_index=True, max_length=64)),
                ('option', models.CharField(blank=True, max_length=255)),
                ('stock', models.IntegerField()),
                ('price', models.IntegerField()),
                ('cost_price', models.IntegerField()),
                ('order_count', models.IntegerField(default=0)),
                ('return_count', models.IntegerField(default=0)),
                ('sales', models.IntegerField(default=0)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventorysnapshot')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.productvariant')),
            ],
            options={
                'indexes': [models.Index(fields=['snapshot', 'variant_code'], name='inventory_i_snapsho_8b581e_idx'), models.Index(fields=['product_id'], name='inventory_i_product_8462a4_idx')],
            },
        ),
    ]
