# Generated by Django 4.2.20 on 2025-12-07 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryCategory',
        ),
    ]
