# Generated by Django 4.2.20 on 2026-01-11 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryadjustment_month_inventoryadjustment_year_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryCategory',
        ),
        migrations.RemoveField(
            model_name='inventorysnapshotitem',
            name='snapshot',
        ),
        migrations.RemoveField(
            model_name='inventorysnapshotitem',
            name='variant',
        ),
        migrations.DeleteModel(
            name='InventorySnapshot',
        ),
        migrations.DeleteModel(
            name='InventorySnapshotItem',
        ),
    ]
