# Generated by Django 4.2.20 on 2025-09-12 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_importbatch_importchange'),
        ('inventory', '0002_inventorysnapshot_inventorysnapshotitem'),
    ]

    operations = [
    ]
