# Generated by Django 4.2.24 on 2025-09-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_merge_20250912_1722"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="importchange",
            name="batch",
        ),
        migrations.RemoveField(
            model_name="importchange",
            name="product",
        ),
        migrations.RemoveField(
            model_name="importchange",
            name="variant",
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="management_code",
            field=models.CharField(
                blank=True,
                help_text="온라인 품목코드와 매칭용",
                max_length=50,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="ImportBatch",
        ),
        migrations.DeleteModel(
            name="ImportChange",
        ),
    ]
