# Generated by Django 4.2.20 on 2025-07-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_productvariant_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(default='일반', help_text='상품 카테고리 (예: 문구, 도서, 의류 등)', max_length=50),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
