# Generated by Django 4.2.20 on 2025-12-07 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_inventorysnapshotitem_snapshot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='management_code',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='order_count',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='return_count',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='big_category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='middle_category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='online_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='detail_option',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(default='일반', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='ProductVariantStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('warehouse_stock_start', models.IntegerField(default=0)),
                ('store_stock_start', models.IntegerField(default=0)),
                ('inbound_quantity', models.IntegerField(default=0)),
                ('store_sales', models.IntegerField(default=0)),
                ('online_sales', models.IntegerField(default=0)),
                ('stock_adjustment', models.IntegerField(default=0)),
                ('stock_adjustment_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productvariant')),
            ],
            options={
                'unique_together': {('year', 'month', 'variant')},
            },
        ),
    ]
