# Generated by Django 4.2.20 on 2026-01-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_delete_inventorycategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantstatus',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
