# Generated by Django 4.2.20 on 2025-05-01 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_productvariant_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='product_code',
            new_name='product_id',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.inventoryitem'),
        ),
    ]
