# Generated by Django 4.2.24 on 2025-09-19 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_remove_importchange_batch_and_more"),
    ]

    operations = []
