# Generated by Django 4.2.20 on 2025-12-13 03:17

import apps.inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_inventoryitem_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariantstatus',
            name='stock_adjustment',
        ),
        migrations.RemoveField(
            model_name='productvariantstatus',
            name='stock_adjustment_reason',
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='month',
            field=models.IntegerField(default=apps.inventory.models.current_month),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='year',
            field=models.IntegerField(default=apps.inventory.models.current_year),
        ),
    ]
