# Generated by Django 4.2.20 on 2025-05-01 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_product_code_inventoryitem_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='product_id',
            new_name='product_code',
        ),
    ]
