# Generated by Django 4.2.20 on 2025-06-04 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_product_id_inventoryitem_product_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='product_code',
            new_name='product_id',
        ),
    ]
