# Generated by Django 4.2.20 on 2025-12-15 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_productvariantstatus_stock_adjustment_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'option', 'detail_option')},
        ),
    ]
