# Generated by Django 4.2.20 on 2025-07-19 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_saleschannel_salestransaction_salestransactionitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='product_code',
            field=models.CharField(db_column='product_id', default='P00000', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.inventoryitem'),
        ),
    ]
