# Generated by Django 4.2.23 on 2025-09-18 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_merge_20250916_1630'),
        ('inventory', '0006_backfill_inventorycategory'),
    ]

    operations = [
    ]
