# Generated by Django 4.2.20 on 2025-06-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_productvariant_description_productvariant_memo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='order_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='return_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
