# Generated by Django 4.2.20 on 2025-07-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_inventoryitem_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='product_code',
            field=models.CharField(db_column='product_id', default='P00000', max_length=50, unique=True),
        ),
    ]
