# Generated by Django 4.2.22 on 2025-09-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_merge_20250918_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importchange',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='importchange',
            name='product',
        ),
        migrations.RemoveField(
            model_name='importchange',
            name='variant',
        ),
        migrations.AlterField(
            model_name='inventorycategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='ImportBatch',
        ),
        migrations.DeleteModel(
            name='ImportChange',
        ),
    ]
