# Generated by Django 4.2.20 on 2025-07-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='denied', max_length=10),
        ),
    ]
