# Generated by Django 4.2.20 on 2025-07-19 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='allowed_tabs',
            field=models.JSONField(blank=True, default=list, help_text='사용자별 접근 허용 탭 목록'),
        ),
        migrations.AddField(
            model_name='employee',
            name='annual_leave_days',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('STAFF', 'Staff'), ('INTERN', 'Intern')], default='STAFF', max_length=10),
        ),
        migrations.CreateModel(
            name='VacationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('VACATION', '연차'), ('HALF_DAY_AM', '오전 반차'), ('HALF_DAY_PM', '오후 반차'), ('SICK', '병가'), ('OTHER', '기타')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', '대기중'), ('APPROVED', '승인됨'), ('REJECTED', '거절됨'), ('CANCELLED', '취소됨')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
