# Generated by Django 4.2.20 on 2025-07-23 10:11

import apps.hr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_employee_allowed_tabs_employee_annual_leave_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='employee',
            name='allowed_tabs',
            field=models.JSONField(blank=True, default=apps.hr.models.Employee.default_allowed_tabs, help_text='사용자별 접근 허용 탭 목록'),
        ),
    ]
