# Generated by Django 4.2.22 on 2025-09-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_add_gender_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
