# Generated by Django 4.2.22 on 2025-09-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_remove_employee_full_name_employee_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='DENIED', max_length=10),
        ),
    ]
