# Generated by Django 4.2.20 on 2025-09-12 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_remove_employee_full_name_and_more'),
        ('hr', '0008_remove_employee_full_name_alter_employee_status'),
    ]

    operations = [
    ]
