# Generated by Django 4.2.22 on 2025-09-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_merge_20250912_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationrequest',
            name='leave_type',
            field=models.CharField(choices=[('VACATION', '연차'), ('HALF_DAY_AM', '오전 반차'), ('HALF_DAY_PM', '오후 반차'), ('SICK', '병가'), ('OTHER', '기타'), ('WORK', '근무')], max_length=20),
        ),
    ]
