# Generated by Django 4.2.20 on 2025-09-22 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('contact', models.CharField(max_length=20)),
                ('manager', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_price', models.PositiveIntegerField(default=0)),
                ('lead_time_days', models.IntegerField(default=3)),
                ('is_primary', models.BooleanField(default=False)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productvariant')),
            ],
            options={
                'unique_together': {('supplier', 'variant')},
            },
        ),
        migrations.AddField(
            model_name='supplier',
            name='variants',
            field=models.ManyToManyField(related_name='suppliers', through='supplier.SupplierVariant', to='inventory.productvariant'),
        ),
    ]
