# Generated by Django 4.2.20 on 2025-06-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliervariant',
            name='cost_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='suppliervariant',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suppliervariant',
            name='lead_time_days',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterModelTable(
            name='suppliervariant',
            table=None,
        ),
    ]
