# Generated by Django 4.2.20 on 2025-11-10 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='variants',
        ),
        migrations.DeleteModel(
            name='SupplierVariant',
        ),
    ]
